# Generated by Django 5.0.6 on 2026-06-30 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Nama')),
                ('actor_jabatan', models.CharField(blank=True, default='', max_length=255, verbose_name='Jabatan')),
                ('actor_unit', models.CharField(blank=True, default='', max_length=255, verbose_name='Unit/Direktorat')),
                ('actor_role', models.CharField(blank=True, default='', max_length=30, verbose_name='Role')),
                ('action', models.CharField(choices=[('satker_create', 'Tambah Satker'), ('satker_update', 'Ubah Satker'), ('satker_deactivate', 'Nonaktifkan Satker'), ('satker_delete', 'Hapus Satker'), ('export_excel', 'Unduh Data (Excel)'), ('login', 'Login')], db_index=True, max_length=40, verbose_name='Aksi')),
                ('description', models.CharField(blank=True, default='', max_length=512, verbose_name='Keterangan')),
                ('target_type', models.CharField(blank=True, default='', max_length=50)),
                ('target_id', models.CharField(blank=True, default='', max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Alamat IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Waktu')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL, verbose_name='Pengguna')),
            ],
            options={
                'verbose_name': 'Log Aktivitas',
                'verbose_name_plural': 'Log Aktivitas',
                'db_table': 'activity_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='activity_lo_created_3aa675_idx'), models.Index(fields=['action', '-created_at'], name='activity_lo_action_61fa17_idx')],
            },
        ),
    ]
