# Generated by Django 5.0.6 on 2026-06-23 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EselonI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255, unique=True, verbose_name='Nama')),
                ('jenis', models.CharField(choices=[('kedeputian', 'Kedeputian'), ('sekretariat', 'Sekretariat'), ('unit_kerja', 'Unit Kerja')], default='kedeputian', max_length=20, verbose_name='Jenis')),
                ('urutan', models.PositiveSmallIntegerField(default=0, help_text='Digunakan untuk mengurutkan tampilan di UI', verbose_name='Urutan tampil')),
            ],
            options={
                'verbose_name': 'Eselon I',
                'verbose_name_plural': 'Eselon I',
                'db_table': 'organisasi_eselon_i',
                'ordering': ['urutan', 'nama'],
            },
        ),
        migrations.CreateModel(
            name='EselonII',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255, unique=True, verbose_name='Nama')),
                ('eselon_i', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unit_eselon_ii', to='organisasi.eseloni', verbose_name='Eselon I')),
            ],
            options={
                'verbose_name': 'Eselon II',
                'verbose_name_plural': 'Eselon II',
                'db_table': 'organisasi_eselon_ii',
                'ordering': ['eselon_i__urutan', 'nama'],
            },
        ),
    ]
