# Generated by Django 5.0.6 on 2026-06-23 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('staff', 'Staff')], default='staff', max_length=20, verbose_name='Role'),
        ),
    ]
